# Generated by Django 5.2.3 on 2025-07-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_aboutme_contact_service_remove_project_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='videos',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
